---
# auto-reload when files change (`watch: false` to disable)
watch: false
# values of custom fields (defined in src/settings.yml)
custom_fields: {}

# Time zone IANA identifier to inject into trmnl.user; see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
time_zone: America/Chicago

# override variables
variables:
  trmnl:
    user:
      name: Joe Bibby
    plugin_settings:
      instance_name: Wisdom Project Quotes
