- keyname: author_bio
  field_type: author_bio
  name: About This Plugin
  description: "Display a daily quote from <a href=\"http://wisdom.limo\" target=\"_blank\">Merlin Mann's \"The Wisdom Project\" - http://wisdom.limo</a>"
  help_text: |
    “Brief introductory remarks regarding the Project:<br/>
    - The ideas on offer here are based on my own experiences and sensibilities. They are mostly things that, above all, I have needed to learn.<br/>
    - As it happens, most of the ideas have been painful to learn and even more difficult to practice.<br/>
    - Some of the ideas are, admittedly, just my opinion.<br/>
    - Many of the ideas will seem to contradict one other. Unfortunately, that doesn't mean one of them has to be wrong.<br/>
    - None of the ideas will be true for every person or for all times. In the event that you ever successfully identify ideas that are true for every person and for all times, you may wish to start a religion.”<br/>
    Merlin Mann
  category: "life,productivity"
  github_url: "https://github.com/VisualYeti/wisdom_trmnl"
  email_address: "support@visualyeti.com"
  learn_more_url: "http://wisdom.limo"
- keyname: quote_size
  field_type: select
  name: Full View Quote Size
  default: 20
  optional: true
  options:
  - Extra Small: "5"
  - Small: "10"
  - Medium: "20"
  - Large: "30"
- keyname: quote_font
  field_type: select
  name: Quote Font
  default: Joan
  optional: true
  options:
  - Joan
  - Caudex
  - Old Standard TT
  - Raleway
  - Rubik
  - Default TRMNL Fonts: TRMNL